#!/bin/bash
## This is a version of the launcher script which run on the src directory - paths are hard coded atm. Configure below:

SRC_DIR=~/pyflag/
INSTALL_DIR=/var/tmp/build/pyflag/

######### END CONFIGURATION ####################

export PYTHONPATH=$SRC_DIR/src/pyflag:$SRC_DIR/src/:/usr/local/lib/python2.7/site-packages/:/usr/local/lib/python2.6/site-packages/:$INSTALL_DIR/lib/python2.7/site-packages/pyflag:$INSTALL_DIR/lib/python2.6/site-packages/pyflag:/usr/local/lib/python2.5/site-packages/:$INSTALL_DIR/lib/python2.5/site-packages/pyflag

exec /usr/bin/python $SRC_DIR/src/pyflag/FlagHTTPServer.py --plugins=$SRC_DIR/src/plugins $@
